open Core

type t =
  | Name
  | Name_prefix
  | Given_name
  | Middle_name
  | Family_name
  | Name_suffix
  | Nickname
  | Job_title
  | Organization_name
  | Location
  | Full_street_address
  | Street_address_line1
  | Street_address_line2
  | Address_city
  | Address_state
  | Address_city_and_state
  | Sublocality
  | Country_name
  | Postal_code
  | Telephone_number
  | Email_address
  | Url
  | Credit_card_number
  | Credit_card_name
  | Credit_card_given_name
  | Credit_card_middle_name
  | Credit_card_family_name
  | Credit_card_security_code
  | Credit_card_expiration
  | Credit_card_expiration_month
  | Credit_card_expiration_year
  | Credit_card_type
  | Username
  | Password
  | New_password
  | One_time_code
  | Shipment_tracking_number
  | Flight_number
  | Date_time
  | Birthdate
  | Birthdate_day
  | Birthdate_month
  | Birthdate_year
  | Cellular_eid
  | Cellular_imei
[@@deriving bin_io, equal, sexp_of]
