open Core

let max_columns = 64
let max_header_levels = 4
let max_schema_text_bytes = 262_144
let max_active_cells = 16_384
let max_copy_bytes = 65_536

let valid_text ~empty ~limit text =
  (empty || not (String.is_empty text))
  && String.length text <= limit
  && Stdlib.String.is_valid_utf_8 text
  && not (String.contains text '\000')
;;

let valid_id = valid_text ~empty:false ~limit:256

module Pin = struct
  type t =
    | Unpinned
    | Left
  [@@deriving bin_io, equal, sexp_of]
end

module Alignment = struct
  type t =
    | Left
    | Center
    | Right
  [@@deriving bin_io, equal, sexp_of]
end

module Direction = struct
  type t =
    | Ascending
    | Descending
  [@@deriving bin_io, equal, sexp_of]
end

module Column = struct
  type t =
    { id : string
    ; label : string
    ; width : float
    ; min_width : float
    ; max_width : float
    ; pin : Pin.t
    ; alignment : Alignment.t
    ; resizable : bool
    ; movable : bool
    ; sortable : bool
    }
  [@@deriving bin_io, equal, sexp_of]

  let valid t =
    valid_id t.id
    && valid_text ~empty:false ~limit:4096 t.label
    && Float.is_finite t.width
    && Float.is_finite t.min_width
    && Float.is_finite t.max_width
    && Float.(
         20. <= t.min_width
         && t.min_width <= t.width
         && t.width <= t.max_width
         && t.max_width <= 16384.)
  ;;
end

module Group = struct
  type t =
    { label : string
    ; columns : string list
    }
  [@@deriving bin_io, equal, sexp_of]
end

module Schema = struct
  type t =
    { columns : Column.t list
    ; headers : Group.t list list
    }
  [@@deriving bin_io, equal, sexp_of]

  let valid t =
    let ids = List.map t.columns ~f:(fun column -> column.Column.id) in
    let pinned =
      List.take_while t.columns ~f:(fun column -> Pin.equal column.Column.pin Left)
      |> List.length
    in
    let bytes =
      List.sum
        (module Int)
        t.columns
        ~f:(fun column -> String.length column.Column.id + String.length column.label)
      + List.sum
          (module Int)
          t.headers
          ~f:(fun groups ->
            List.sum
              (module Int)
              groups
              ~f:(fun group ->
                String.length group.Group.label
                + List.sum (module Int) group.columns ~f:String.length))
    in
    List.length t.columns <= max_columns
    && List.length t.headers <= max_header_levels
    && List.for_all t.columns ~f:Column.valid
    && (not (List.contains_dup ids ~compare:String.compare))
    && List.for_all (List.drop t.columns pinned) ~f:(fun column ->
      Pin.equal column.Column.pin Unpinned)
    && bytes <= max_schema_text_bytes
    && ((not (List.is_empty t.columns)) || List.is_empty t.headers)
    && Result.is_ok
         (List.fold_result t.headers ~init:Int.Set.empty ~f:(fun upper groups ->
            if
              List.is_empty groups
              || List.length groups > max_columns
              || not
                   (List.equal
                      String.equal
                      (List.concat_map groups ~f:(fun g -> g.Group.columns))
                      ids)
            then Error ()
            else (
              let valid, _, boundaries =
                List.fold
                  groups
                  ~init:(true, 0, Int.Set.empty)
                  ~f:(fun (valid, start, boundaries) group ->
                    let stop = start + List.length group.Group.columns in
                    ( valid
                      && valid_text ~empty:false ~limit:4096 group.label
                      && (not (List.is_empty group.columns))
                      && not (start < pinned && stop > pinned)
                    , stop
                    , Set.add boundaries stop ))
              in
              if valid && Set.is_subset upper ~of_:boundaries
              then Ok boundaries
              else Error ())))
  ;;
end

module Sort = struct
  type t =
    { column : string
    ; direction : Direction.t
    }
  [@@deriving bin_io, equal, sexp_of]
end

module Selection_mode = struct
  type t =
    | Rows
    | Cells
    | Rows_and_cells
  [@@deriving bin_io, equal, sexp_of]
end

module Config = struct
  (** Private bridge revisions, generated by the mounted adapter. Schema revision
      governs authoritative column replacement; query generation fences obsolete
      producer work. Logical row order has its own List_wire.Order revision. *)
  type t =
    { schema_revision : int64
    ; query_generation : int64
    ; schema : Schema.t
    ; sort : Sort.t option
    ; row_height : float
    ; overscan : float
    ; max_active_rows : int64
    ; max_active_cells : int64
    ; selection_mode : Selection_mode.t
    ; column_selection : bool
    ; disabled : bool
    ; scrollbar : bool
    ; label : string
    }
  [@@deriving bin_io, equal, sexp_of]

  let valid t =
    Int64.(t.schema_revision > 0L && t.query_generation >= 0L)
    && Schema.valid t.schema
    && Option.for_all t.sort ~f:(fun sort ->
      List.exists t.schema.columns ~f:(fun column ->
        String.equal column.Column.id sort.Sort.column && column.sortable))
    && Float.is_finite t.row_height
    && Float.(t.row_height >= 20. && t.row_height <= 4096.)
    && Float.is_finite t.overscan
    && Float.(t.overscan >= 0. && t.overscan <= 1_000_000.)
    && Int64.(
         t.max_active_rows >= 1L && t.max_active_rows <= of_int List_wire.max_active_rows)
    && Int64.(t.max_active_cells >= 1L && t.max_active_cells <= of_int max_active_cells)
    && Int64.(
         t.max_active_rows * of_int (List.length t.schema.columns) <= t.max_active_cells)
    && valid_text ~empty:false ~limit:1024 t.label
  ;;
end

module Cell = struct
  (** Retained copy text is separate from child View descriptions. Empty text is
      valid; one cell never owns application data or a formatting callback. *)
  type t =
    { column : string
    ; copy_text : string
    }
  [@@deriving bin_io, equal, sexp_of]

  let valid t =
    valid_id t.column && valid_text ~empty:true ~limit:max_copy_bytes t.copy_text
  ;;
end

module Selection = struct
  type t =
    | Empty
    | Row of int64
    | Column of string
    | Cell of int64 * string
  [@@deriving bin_io, equal, sexp_of]

  let valid = function
    | Empty -> true
    | Row row -> Int64.(row > 0L)
    | Column column -> valid_id column
    | Cell (row, column) -> Int64.(row > 0L) && valid_id column
  ;;
end

module Target = struct
  type t =
    | Set_selection of Selection.t
    | Reveal of int64 * string option
    | Scroll_to of int64 * float
    | Scroll_to_column of string
    | Scroll_to_end
    | Reset_columns
  [@@deriving bin_io, equal, sexp_of]

  let valid = function
    | Set_selection selection -> Selection.valid selection
    | Reveal (row, column) -> Int64.(row > 0L) && Option.for_all column ~f:valid_id
    | Scroll_to (row, offset) ->
      Int64.(row > 0L)
      && Float.is_finite offset
      && Float.(offset >= 0. && offset <= 4096.)
    | Scroll_to_column column -> valid_id column
    | Scroll_to_end | Reset_columns -> true
  ;;
end

module Command = struct
  type t =
    { serial : int64
    ; query_generation : int64
    ; target : Target.t
    }
  [@@deriving bin_io, equal, sexp_of]

  let valid t = Int64.(t.serial > 0L && t.query_generation >= 0L) && Target.valid t.target
end

module Request = struct
  type t =
    | Select of Selection.t
    | Activate of int64 * string option
    | Context of Selection.t
    | Resize of (string * float) list
    | Move of string * string option
    | Sort of string * Direction.t option
    | Copy of Selection.t
  [@@deriving bin_io, equal, sexp_of]

  let valid = function
    | Select selection | Context selection | Copy selection -> Selection.valid selection
    | Activate (row, column) -> Int64.(row > 0L) && Option.for_all column ~f:valid_id
    | Resize widths ->
      (not (List.is_empty widths))
      && List.length widths <= max_columns
      && (not (List.contains_dup (List.map widths ~f:fst) ~compare:String.compare))
      && List.for_all widths ~f:(fun (column, width) ->
        valid_id column
        && Float.is_finite width
        && Float.(width >= 20. && width <= 16384.))
    | Move (column, before) ->
      valid_id column
      && Option.for_all before ~f:(fun target ->
        valid_id target && not (String.equal column target))
    | Sort (column, _) -> valid_id column
  ;;
end

module Input = struct
  type t =
    { schema_revision : int64
    ; query_generation : int64
    ; request : Request.t
    }
  [@@deriving bin_io, equal, sexp_of]

  let valid t =
    Int64.(t.schema_revision > 0L && t.query_generation >= 0L) && Request.valid t.request
  ;;
end
