use gpuio_protocol::calendar::*;

fn date(year: i64, month: i64, day: i64) -> Date {
    Date::from_ymd(year, month, day).unwrap()
}
fn range(first: Date, last: Date) -> Range {
    Range::new(first, last).unwrap()
}

#[test]
fn civil_reference_vectors_and_untrusted_boundaries() {
    // Independently checked using Python datetime's proleptic Gregorian ordinal,
    // then shared as constants with Core.Date tests; not generated by this codec.
    for (year, month, day, ordinal, weekday) in [
        (1, 1, 1, 0, 1),
        (1600, 2, 29, 584081, 2),
        (1900, 3, 1, 693654, 4),
        (1970, 1, 1, 719162, 4),
        (2000, 1, 1, 730119, 6),
        (2000, 2, 29, 730178, 2),
        (2024, 2, 29, 738944, 4),
        (2100, 3, 1, 766703, 1),
        (2400, 2, 29, 876275, 2),
        (9999, 12, 31, 3652058, 5),
    ] {
        let date = date(year, month, day);
        assert_eq!(date.ordinal(), ordinal);
        assert_eq!(date.ymd(), (year, month, day));
        assert_eq!(date.weekday(), weekday);
        assert_eq!(Date::from_ordinal(ordinal), Some(date));
    }
    for ordinal in [i64::MIN, -1, 3652059, i64::MAX] {
        assert!(Date::from_ordinal(ordinal).is_none());
    }
    for (year, month, day) in [
        (0, 1, 1),
        (10000, 1, 1),
        (1900, 2, 29),
        (2100, 2, 29),
        (2024, 0, 1),
        (2024, 13, 1),
        (2024, 4, 31),
        (2024, 2, 0),
        (i64::MAX, 1, 1),
        (1, i64::MAX, 1),
        (1, 1, i64::MAX),
    ] {
        assert!(Date::from_ymd(year, month, day).is_none());
    }
    assert!(Range::new(Date::MAX, Date::MIN).is_none());
    assert!(Date::MAX.shift(i64::MAX).is_none());
    assert!(Date::MIN.shift(i64::MIN).is_none());
    for months in [-1, i64::MIN] {
        assert!(Month::from_date(Date::MIN).shift(months).is_none());
    }
    for months in [1, i64::MAX] {
        assert!(Month::from_date(Date::MAX).shift(months).is_none());
    }
    assert_eq!(
        Month::new(1, 1).unwrap().shift(119987),
        Month::new(9999, 12)
    );
}

#[test]
fn complete_gregorian_cycle_and_month_grids() {
    let first = date(2000, 1, 1);
    for offset in 0..146097 {
        let d = first.shift(offset).unwrap();
        let (year, month, day) = d.ymd();
        assert_eq!(date(year, month, day), d);
        assert_eq!(d.weekday(), (first.weekday() + offset) % 7);
    }
    for year in 2000..2400 {
        for month in 1..=12 {
            let month = Month::new(year, month).unwrap();
            for weekday in 0..7 {
                let days = month.days(weekday).unwrap().map(Option::unwrap);
                assert_eq!(days[0].weekday(), weekday);
                for pair in days.windows(2) {
                    assert_eq!(pair[1].ordinal() - pair[0].ordinal(), 1);
                }
                let own: Vec<_> = days
                    .into_iter()
                    .filter(|&d| d >= month.first_day() && d <= month.last_day())
                    .collect();
                assert_eq!(own.first(), Some(&month.first_day()));
                assert_eq!(own.last(), Some(&month.last_day()));
                assert_eq!(own.len() as i64, month.last_day().ymd().2);
            }
        }
    }
    for boundary in [Date::MIN, Date::MAX] {
        let month = Month::from_date(boundary);
        for weekday in 0..7 {
            let days = month.days(weekday).unwrap();
            assert!(days.contains(&Some(boundary)));
            for d in days.into_iter().flatten() {
                assert!((Date::MIN..=Date::MAX).contains(&d));
            }
        }
        assert!(month.days(-1).is_none());
        assert!(month.days(7).is_none());
    }
}

#[test]
fn canonical_constraints_and_input_quotas() {
    let a = date(2024, 1, 1);
    let constraints = Constraints::new(
        Date::MIN,
        Date::MAX,
        vec![a, a],
        vec![
            range(a.shift(2).unwrap(), a.shift(5).unwrap()),
            range(a, a.shift(1).unwrap()),
            range(a.shift(4).unwrap(), a.shift(9).unwrap()),
        ],
        vec![6, 0, 6],
        RangePolicy::EveryDay,
    )
    .unwrap();
    assert_eq!(constraints.disabled_dates(), &[a]);
    assert_eq!(
        constraints.disabled_ranges(),
        &[range(a, a.shift(9).unwrap())]
    );
    assert_eq!(constraints.disabled_weekdays(), &[0, 6]);
    assert!(
        Constraints::new(
            Date::MIN,
            Date::MAX,
            vec![a; 513],
            vec![],
            vec![],
            RangePolicy::EveryDay
        )
        .is_none()
    );
    assert!(
        Constraints::new(
            Date::MIN,
            Date::MAX,
            vec![],
            vec![range(a, a); 129],
            vec![],
            RangePolicy::EveryDay
        )
        .is_none()
    );
    for weekdays in [vec![0; 8], vec![-1], vec![7]] {
        assert!(
            Constraints::new(
                Date::MIN,
                Date::MAX,
                vec![],
                vec![],
                weekdays,
                RangePolicy::EveryDay
            )
            .is_none()
        );
    }
    assert!(
        Constraints::new(
            Date::MAX,
            Date::MIN,
            vec![],
            vec![],
            vec![],
            RangePolicy::EveryDay
        )
        .is_none()
    );
    let none = Constraints::new(
        Date::MIN,
        Date::MAX,
        vec![],
        vec![],
        (0..7).collect(),
        RangePolicy::EveryDay,
    )
    .unwrap();
    assert!(!none.allows(a));
    assert!(none.allows_selection(Selection::Empty, Mode::Range));
    assert!(none.allows_selection(Selection::Empty, Mode::Single));
}

#[test]
fn selection_restarts_and_partial_changes_are_not_lost() {
    let a = date(2024, 4, 1);
    let constraints = Constraints::new(
        Date::MIN,
        Date::MAX,
        vec![a.shift(1).unwrap()],
        vec![],
        vec![],
        RangePolicy::EveryDay,
    )
    .unwrap();
    let click = |selection, offset| {
        activate(
            selection,
            a.shift(offset).unwrap(),
            Mode::Range,
            &constraints,
        )
    };
    let later = click(Selection::Empty, 2).unwrap();
    assert_eq!(later, Selection::RangeStart(a.shift(2).unwrap()));
    let start = click(later, 0).unwrap();
    assert_eq!(start, Selection::RangeStart(a));
    assert_eq!(click(start, 2), Err(SelectionError::DisabledInterior));
    assert_eq!(click(start, 1), Err(SelectionError::DisabledDate));
    let completed = click(start, 0).unwrap();
    assert_eq!(completed, Selection::Range(range(a, a)));
    assert!(completed.is_complete());
    assert_eq!(click(completed, 2).unwrap(), later);
    assert_eq!(
        click(Selection::Single(a), 2),
        Err(SelectionError::WrongMode)
    );
    let constraints = Constraints::new(
        Date::MIN,
        Date::MAX,
        vec![a],
        vec![],
        vec![],
        RangePolicy::EveryDay,
    )
    .unwrap();
    assert_eq!(
        activate(start, a.shift(2).unwrap(), Mode::Range, &constraints),
        Err(SelectionError::DisabledDate)
    );
}

#[test]
fn bounded_range_checks_match_daily_reference() {
    let a = date(2024, 1, 1);
    for policy in [RangePolicy::EveryDay, RangePolicy::EndpointsOnly] {
        let c = Constraints::new(
            date(2024, 1, 2),
            date(2024, 3, 10),
            vec![date(2024, 1, 9), date(2024, 2, 1)],
            vec![
                range(date(2024, 1, 15), date(2024, 1, 17)),
                range(date(2024, 2, 27), date(2024, 3, 1)),
            ],
            vec![0, 6],
            policy,
        )
        .unwrap();
        for first in 0..=70 {
            for last in first..=70 {
                let selection =
                    Selection::Range(range(a.shift(first).unwrap(), a.shift(last).unwrap()));
                let expected = match policy {
                    RangePolicy::EveryDay => {
                        (first..=last).all(|offset| c.allows(a.shift(offset).unwrap()))
                    }
                    RangePolicy::EndpointsOnly => {
                        c.allows(a.shift(first).unwrap()) && c.allows(a.shift(last).unwrap())
                    }
                };
                assert_eq!(c.allows_selection(selection, Mode::Range), expected);
            }
        }
    }
    let all = Selection::Range(range(Date::MIN, Date::MAX));
    assert!(Constraints::unrestricted().allows_selection(all, Mode::Range));
    for weekday in 0..7 {
        let c = Constraints::new(
            Date::MIN,
            Date::MAX,
            vec![],
            vec![],
            vec![weekday],
            RangePolicy::EveryDay,
        )
        .unwrap();
        assert!(!c.allows_selection(all, Mode::Range));
    }
}
