//! Semantic input hints from the pinned public component vocabulary.
use binprot::macros::BinProtWrite;
#[derive(Clone, Copy, Debug, PartialEq, Eq, BinProtWrite)]
pub enum Hint {
    Name,
    NamePrefix,
    GivenName,
    MiddleName,
    FamilyName,
    NameSuffix,
    Nickname,
    JobTitle,
    OrganizationName,
    Location,
    FullStreetAddress,
    StreetAddressLine1,
    StreetAddressLine2,
    AddressCity,
    AddressState,
    AddressCityAndState,
    Sublocality,
    CountryName,
    PostalCode,
    TelephoneNumber,
    EmailAddress,
    Url,
    CreditCardNumber,
    CreditCardName,
    CreditCardGivenName,
    CreditCardMiddleName,
    CreditCardFamilyName,
    CreditCardSecurityCode,
    CreditCardExpiration,
    CreditCardExpirationMonth,
    CreditCardExpirationYear,
    CreditCardType,
    Username,
    Password,
    NewPassword,
    OneTimeCode,
    ShipmentTrackingNumber,
    FlightNumber,
    DateTime,
    Birthdate,
    BirthdateDay,
    BirthdateMonth,
    BirthdateYear,
    CellularEid,
    CellularImei,
}
impl Hint {
    pub fn from_tag(tag: u8) -> Option<Self> {
        Some(match tag {
            0 => Self::Name,
            1 => Self::NamePrefix,
            2 => Self::GivenName,
            3 => Self::MiddleName,
            4 => Self::FamilyName,
            5 => Self::NameSuffix,
            6 => Self::Nickname,
            7 => Self::JobTitle,
            8 => Self::OrganizationName,
            9 => Self::Location,
            10 => Self::FullStreetAddress,
            11 => Self::StreetAddressLine1,
            12 => Self::StreetAddressLine2,
            13 => Self::AddressCity,
            14 => Self::AddressState,
            15 => Self::AddressCityAndState,
            16 => Self::Sublocality,
            17 => Self::CountryName,
            18 => Self::PostalCode,
            19 => Self::TelephoneNumber,
            20 => Self::EmailAddress,
            21 => Self::Url,
            22 => Self::CreditCardNumber,
            23 => Self::CreditCardName,
            24 => Self::CreditCardGivenName,
            25 => Self::CreditCardMiddleName,
            26 => Self::CreditCardFamilyName,
            27 => Self::CreditCardSecurityCode,
            28 => Self::CreditCardExpiration,
            29 => Self::CreditCardExpirationMonth,
            30 => Self::CreditCardExpirationYear,
            31 => Self::CreditCardType,
            32 => Self::Username,
            33 => Self::Password,
            34 => Self::NewPassword,
            35 => Self::OneTimeCode,
            36 => Self::ShipmentTrackingNumber,
            37 => Self::FlightNumber,
            38 => Self::DateTime,
            39 => Self::Birthdate,
            40 => Self::BirthdateDay,
            41 => Self::BirthdateMonth,
            42 => Self::BirthdateYear,
            43 => Self::CellularEid,
            44 => Self::CellularImei,
            _ => return None,
        })
    }
    /// Pinned macOS NSTextContent string; not a promise of autofill support.
    pub fn macos_value(self) -> Option<&'static str> {
        match self {
            Self::Name => Some("name"),
            Self::NamePrefix => Some("honorific-prefix"),
            Self::GivenName => Some("given-name"),
            Self::MiddleName => Some("additional-name"),
            Self::FamilyName => Some("family-name"),
            Self::NameSuffix => Some("honorific-suffix"),
            Self::Nickname => Some("nickname"),
            Self::JobTitle => Some("organization-title"),
            Self::OrganizationName => Some("organization"),
            Self::Location => Some("location"),
            Self::FullStreetAddress => Some("street-address"),
            Self::StreetAddressLine1 => Some("address-line1"),
            Self::StreetAddressLine2 => Some("address-line2"),
            Self::AddressCity => Some("address-level2"),
            Self::AddressState => Some("address-level1"),
            Self::AddressCityAndState => Some("address-level1+2"),
            Self::Sublocality => Some("address-level3"),
            Self::CountryName => Some("country-name"),
            Self::PostalCode => Some("postal-code"),
            Self::TelephoneNumber => Some("tel"),
            Self::EmailAddress => Some("email"),
            Self::Url => Some("url"),
            Self::CreditCardNumber => Some("cc-number"),
            Self::CreditCardName => Some("cc-name"),
            Self::CreditCardGivenName => Some("cc-given-name"),
            Self::CreditCardMiddleName => Some("cc-additional-name"),
            Self::CreditCardFamilyName => Some("cc-family-name"),
            Self::CreditCardSecurityCode => Some("cc-csc"),
            Self::CreditCardExpiration => Some("cc-exp"),
            Self::CreditCardExpirationMonth => Some("cc-exp-month"),
            Self::CreditCardExpirationYear => Some("cc-exp-year"),
            Self::CreditCardType => Some("cc-type"),
            Self::Username => Some("username"),
            Self::Password => Some("password"),
            Self::NewPassword => Some("new-password"),
            Self::OneTimeCode => Some("one-time-code"),
            Self::ShipmentTrackingNumber => Some("shipment-tracking-number"),
            Self::FlightNumber => Some("flight-number"),
            Self::DateTime => Some("date-time"),
            Self::Birthdate => Some("bday"),
            Self::BirthdateDay => Some("bday-day"),
            Self::BirthdateMonth => Some("bday-month"),
            Self::BirthdateYear => Some("bday-year"),
            Self::CellularEid | Self::CellularImei => None,
        }
    }
    pub fn is_password(self) -> bool {
        matches!(self, Self::Password | Self::NewPassword)
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, BinProtWrite)]
pub enum Unavailability {
    Backend,
    Mapping,
    NativeView,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, BinProtWrite)]
pub enum Status {
    Inactive(Option<Hint>),
    Exposed(Hint),
    Unavailable(Hint, Unavailability),
}
