use gpuio_protocol::{NodeId, WindowId, v1::*};
pub fn request() -> Message {
    let fields = vec![
        Field::Display(2),
        Field::Visibility(0),
        Field::Direction(1),
        Field::Wrap(1),
        Field::Grow(1.),
        Field::Shrink(0.),
        Field::Basis(Length::Auto),
        Field::AlignItems(4),
        Field::AlignSelf(6),
        Field::AlignContent(7),
        Field::JustifyContent(6),
        Field::RowGap(Length::Px(8.)),
        Field::ColumnGap(Length::Percent(2.)),
        Field::GridColumns(3),
        Field::GridRows(2),
        Field::GridColumnMinimum(1),
        Field::GridRowMinimum(2),
        Field::Width(Length::Percent(100.)),
        Field::Height(Length::Px(480.)),
        Field::MinWidth(Length::Px(100.)),
        Field::MinHeight(Length::Px(20.)),
        Field::MaxWidth(Length::Px(800.)),
        Field::MaxHeight(Length::Auto),
        Field::PaddingTop(Length::Px(1.)),
        Field::PaddingRight(Length::Px(2.)),
        Field::PaddingBottom(Length::Px(3.)),
        Field::PaddingLeft(Length::Percent(4.)),
        Field::MarginTop(Length::Px(-1.)),
        Field::MarginRight(Length::Auto),
        Field::MarginBottom(Length::Px(-3.)),
        Field::MarginLeft(Length::Percent(4.)),
        Field::Position(1),
        Field::Top(Length::Px(10.)),
        Field::Right(Length::Auto),
        Field::Bottom(Length::Percent(20.)),
        Field::Left(Length::Px(-5.)),
        Field::Background(Fill::LinearGradient(
            45.,
            Color::Rgba(0xff0000ff),
            0.,
            Color::Rgba(0x0000ffff),
            1.,
        )),
        Field::Foreground(Color::Rgba(0x112233ff)),
        Field::Opacity(0.75),
        Field::BorderTopWidth(1.),
        Field::BorderRightWidth(2.),
        Field::BorderBottomWidth(3.),
        Field::BorderLeftWidth(4.),
        Field::TopLeftRadius(5.),
        Field::TopRightRadius(6.),
        Field::BottomLeftRadius(7.),
        Field::BottomRightRadius(8.),
        Field::BorderColor(Color::Rgba(0xffffffff)),
        Field::Shadows(vec![Shadow {
            color: Color::Rgba(0x00000088),
            offset_x: -2.,
            offset_y: 3.,
            blur: 4.,
            spread: -1.,
            inset: true,
        }]),
        Field::FontSize(16.),
        Field::FontFamily("λ family".into()),
        Field::FontWeight(600),
        Field::TextAlign(1),
        Field::LineHeight(Length::Percent(150.)),
        Field::WhiteSpace(1),
        Field::TextOverflow(1),
        Field::LineClamp(3),
        Field::TextDecoration(3),
        Field::OverflowX(3),
        Field::OverflowY(2),
        Field::Cursor(8),
        Field::PointerEvents(false),
        Field::UserSelect(true),
        Field::SelectionColor(Color::Rgba(0xabcdef80)),
        Field::AccessibleName("Copy response".into()),
    ];
    let id = NodeId::from_parts(0, 1).unwrap();
    Message::Apply(Transaction {
        window: WindowId::from_parts(0, 1).unwrap(),
        base: 0,
        revision: 1,
        operations: vec![
            Op::Create(id, Kind::Container, "".into(), None),
            Op::SetStyle(
                id,
                vec![
                    Style::Fields(fields),
                    Style::State(
                        1,
                        vec![Field::Background(Fill::Solid(Color::Rgba(0xffffffff)))],
                    ),
                ],
            ),
            Op::SetRoot(Some(id)),
        ],
    })
}
