(library
 (name gpuio_chart_tests)
 (libraries core gpuio gpuio.protocol eio_main)
 (inline_tests
  (deps
   (sandbox preserve_file_kind)
   chart-v1-data.hex
   chart-v4-node-labels-view.hex
   chart-v1-selection.hex))
 (preprocess
  (pps ppx_jane)))

(copy_files ../fixtures/chart-v1-data.hex)

(copy_files ../fixtures/chart-v4-node-labels-view.hex)

(copy_files ../fixtures/chart-v1-selection.hex)
