(rule
 (targets libgpuio_native.a link_flags.sexp c_link_flags.sexp)
 (deps
  (sandbox none)
  (env_var CARGO_TARGET_DIR)
  (source_tree ../../rust)
  (source_tree ../../vendor/gpui-base)
  ../../Cargo.toml
  ../../Cargo.lock
  ../../rust-toolchain.toml
  ../../scripts/build_native.py)
 (action
  (run python3 ../../scripts/build_native.py %{profile} gpuio-native)))

(library
 (name gpuio_native)
 (public_name gpuio.native)
 (modes native)
 (no_dynlink)
 (libraries core gpuio.protocol unix)
 (foreign_archives gpuio_native)
 (c_library_flags
  (:include c_link_flags.sexp))
 (preprocess
  (pps ppx_jane)))
