(library
 (name gpuio_view_api_tests)
 (libraries core gpuio gpuio.protocol eio_main)
 (inline_tests
  (deps
   (sandbox preserve_file_kind)
   style-v1.hex
   controls-v1.hex
   choice-v1-request.hex
   choice-v1-events.hex
   combobox-v1-request.hex
   combobox-v1-events.hex
   focus-v1-request.hex
   focus-v1-events.hex
   editor-v1-requests.hex
   editor-v1-events.hex))
 (preprocess
  (pps ppx_jane)))

(copy_files ../fixtures/style-v1.hex)

(copy_files ../fixtures/controls-v1.hex)

(copy_files ../fixtures/choice-v1-request.hex)

(copy_files ../fixtures/choice-v1-events.hex)

(copy_files ../fixtures/editor-v1-requests.hex)

(copy_files ../fixtures/editor-v1-events.hex)

(copy_files ../fixtures/combobox-v1-request.hex)

(copy_files ../fixtures/combobox-v1-events.hex)

(copy_files ../fixtures/focus-v1-request.hex)

(copy_files ../fixtures/focus-v1-events.hex)
